version: "3"

services:
  db:
    image: postgres:14.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usr -d ranks" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - .:/app
      - type: volume
        source: data
        target: /var/lib/postgres/data
        volume:
          nocopy: true
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

volumes:
  data:
